[2023-07-12T11:01:11.175+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: create_table.create_table manual__2023-07-12T11:01:09.663192+00:00 [queued]>
[2023-07-12T11:01:11.186+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: create_table.create_table manual__2023-07-12T11:01:09.663192+00:00 [queued]>
[2023-07-12T11:01:11.187+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-07-12T11:01:11.188+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-07-12T11:01:11.190+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-07-12T11:01:11.207+0000] {taskinstance.py:1304} INFO - Executing <Task(SnowflakeOperator): create_table> on 2023-07-12 11:01:09.663192+00:00
[2023-07-12T11:01:11.213+0000] {standard_task_runner.py:55} INFO - Started process 1300 to run task
[2023-07-12T11:01:11.218+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'create_table', 'create_table', 'manual__2023-07-12T11:01:09.663192+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/t.py', '--cfg-path', '/tmp/tmppfoeoyrk']
[2023-07-12T11:01:11.221+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask create_table
[2023-07-12T11:01:11.307+0000] {task_command.py:389} INFO - Running <TaskInstance: create_table.create_table manual__2023-07-12T11:01:09.663192+00:00 [running]> on host 38053bc535fb
[2023-07-12T11:01:11.385+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_table
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2023-07-12T11:01:09.663192+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-12T11:01:09.663192+00:00
[2023-07-12T11:01:11.387+0000] {sql.py:253} INFO - Executing: 
CREATE OR REPLACE TABLE my_table (
    id INT,
    name VARCHAR,
    age INT
);
[2023-07-12T11:01:11.408+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 254, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_connection` isn't defined
[2023-07-12T11:01:11.414+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=create_table, task_id=create_table, execution_date=20230712T110109, start_date=20230712T110111, end_date=20230712T110111
[2023-07-12T11:01:11.427+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 3 for task create_table (The conn_id `snowflake_connection` isn't defined; 1300)
[2023-07-12T11:01:11.471+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-07-12T11:01:11.491+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
